name: CI

on:
  push:
      branches: [ main ]

jobs: 
  integrationTests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm start &
      - run: npx newman run tests/D03_jpcc.json

      
     